Feature/0296 possibility to update video streaming capabilities
smartdevicelink/sdl_hmi_integration_guidelines pull request #223
Opened 2020-08-07 10:11 UTC by KhrystynaDubovyk

Guidelines updates according to the proposal [SDL-0296](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0296-Update-video-streaming-capabilities-during-ignition-cycle.md)

This PR is **not ready** for review.

### Summary
**Changelog**
Structs/index.md - add `AppCapability` struct, add `additionalVideoStreamingCapabilities` param
Enums/index.md - add `AppCapabilityType`

**Create** 
BC.OnAppCapabilityUpdated - index and assets

**Update**
BC.OnSystemCapabilityUpdated - update index.md; add OnSystemCapabilityUpdated_VIDEO_STREAMING diagram

2020-08-17 14:48 UTC, LitvinenkoIra commented on docs/BasicCommunication/OnAppCapabilityUpdated/idex.md
> +## OnAppCapabilityUpdated
typo -> idex.md -> index.md

2020-08-17 14:51 UTC, LitvinenkoIra commented on docs/BasicCommunication/OnAppCapabilityUpdated/idex.md
> +HMI may switch video streaming resolution according to values provided by application in OnAppCapabilityUpdated notification. (_see also [OnSystemCapabilityUpdated](../OnSystemCapabilityUpdated/index
If HMI doesn't receive OnAppCapability updated - HMI should not send OnSysCapabilityUpdated and the user should not be able to change the resolution

2020-08-17 14:52 UTC, LitvinenkoIra commented on docs/BasicCommunication/OnAppCapabilityUpdated/idex.md
> +
full-screen mode -> default screen mode

2020-08-17 14:56 UTC, LitvinenkoIra commented on docs/BasicCommunication/OnAppCapabilityUpdated/idex.md
> +HMI may switch video streaming resolution according to values provided by application in OnAppCapabilityUpdated notification. (_see also [OnSystemCapabilityUpdated](../OnSystemCapabilityUpdated/index
of if HMI received OnAppCapabilityUpdated without additionalVideoStCaps inside

2020-08-17 14:58 UTC, LitvinenkoIra commented on docs/BasicCommunication/OnSystemCapabilityUpdated/assets/OnSystemCapabilityUpdated_VIDEO_STREAMING.txt
> +HMI->>SDL:<align:center> BC.OnSystemCapabilityUpdated\n(videoStreamingCapability=VideoStreamingCapability)
need to add app_id as a parameter

2020-08-17 15:02 UTC, LitvinenkoIra commented on docs/Common/Structs/index.md
> +|additionalVideoStreamingCapabilities|Common.VideoStreamingCapability|false|array: true<br>minsize: 0<br>maxsize: 100|
minsize 1

2020-08-18 15:21 UTC, LitvinenkoIra commented
@atiwari9 please review this PR

2020-12-18 08:28 UTC, LitvinenkoIra commented
@jordynmackool @JackLivio This PR is ready for Livio review. Thank you!

2021-01-29 18:58 UTC, ShobhitAd requested changes
A new entry for `OnAppCapabilityUpdated` has to be added in config.json

2021-01-29 18:58 UTC, ShobhitAd commented on docs/BasicCommunication/OnAppCapabilityUpdated/index.md
> +HMI may switch video streaming resolution according to values provided by application in OnAppCapabilityUpdated notification. (_see also [OnSystemCapabilityUpdated](../OnSystemCapabilityUpdated/index
```suggestion
HMI may switch video streaming resolution according to values provided by application in OnAppCapabilityUpdated notification. (_see also [OnSystemCapabilityUpdated](../OnSystemCapabilityUpdated)_)
```

2021-01-29 18:58 UTC, ShobhitAd commented on docs/BasicCommunication/OnAppCapabilityUpdated/index.md
> +### JSON Message Examples
```suggestion
### JSON Message Examples
```

2021-01-29 18:58 UTC, ShobhitAd commented on docs/BasicCommunication/OnAppCapabilityUpdated/index.md
> +   }
```suggestion
   }
}
```

2021-01-29 18:58 UTC, ShobhitAd commented on docs/BasicCommunication/OnSystemCapabilityUpdated/index.md
> +#### Videosteaming Switching Example Notification
```suggestion

#### Videosteaming Switching Example Notification
```

2021-01-29 18:58 UTC, ShobhitAd commented on docs/Common/Structs/index.md
> +|additionalVideoStreamingCapabilities|Common.VideoStreamingCapability|false|array: true<br>minsize: 1<br>maxsize: 100|
```suggestion
|additionalVideoStreamingCapabilities|Common.VideoStreamingCapability|false|array: true<br>minsize: 1<br>maxsize: 100||
```

2021-02-03 12:46 UTC, KhrystynaDubovyk commented
> A new entry for OnAppCapabilityUpdated has to be added in config.json

done in https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/pull/223/commits/49651e176caf80bea2e77ecd5c6709e3f2ba45a3

2021-02-03 14:29 UTC, ShobhitAd requested changes

2021-02-03 14:29 UTC, ShobhitAd commented on docs/BasicCommunication/OnAppCapabilityUpdated/index.md
> +SDL sends OnAppCapabilityUpdated notification to HMI to provide supported by application <abbr title="Video Streaming Capabilities">VSC</abbr>
```suggestion
SDL sends OnAppCapabilityUpdated notification to HMI to provide <abbr title="Video Streaming Capabilities">VSC</abbr> supported by application
```

2021-02-03 14:29 UTC, ShobhitAd commented on docs/BasicCommunication/OnAppCapabilityUpdated/assets/OnAppCapabilityUpdated.txt
> +SDL-->App:<align:center> GetSystemCapability\nsystemCapability=videoStreamingCapability,\n[additionalVideoStreamingCapabilities])
```suggestion
SDL-->App:<align:center> GetSystemCapability\n(systemCapability=videoStreamingCapability,\n[additionalVideoStreamingCapabilities])
```

2021-02-03 14:29 UTC, ShobhitAd commented on docs/BasicCommunication/OnAppCapabilityUpdated/assets/OnAppCapabilityUpdated.txt
> +App->>SDL:<align:center> OnAppCapabilityUpdated\nappCapability=videoStreamingCapability,\n[additionalVideoStreamingCapabilities])
```suggestion
App->>SDL:<align:center> OnAppCapabilityUpdated\n(appCapability=videoStreamingCapability,\n[additionalVideoStreamingCapabilities])
```

2021-02-04 14:19 UTC, ShobhitAd commented
@KhrystynaDubovyk Thank you for making the changes. Could you also please re-generate the sequence diagram `docs/BasicCommunication/OnAppCapabilityUpdated/assets/OnAppCapabilityUpdated.png` based on the changes from https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/pull/223/commits/570f6962d7aaf2a009dd5e6c547e0ab5ae491d43#diff-2db152cf1a1fa3403ab09f6a4b119c395190c5790055dffe0b20d8662e98a9ef

2021-02-04 15:01 UTC, KhrystynaDubovyk commented
> @KhrystynaDubovyk Thank you for making the changes. Could you also please re-generate the sequence diagram `docs/BasicCommunication/OnAppCapabilityUpdated/assets/OnAppCapabilityUpdated.png` based on the changes from [570f696#diff-2db152cf1a1fa3403ab09f6a4b119c395190c5790055dffe0b20d8662e98a9ef](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/commit/570f6962d7aaf2a009dd5e6c547e0ab5ae491d43#diff-2db152cf1a1fa3403ab09f6a4b119c395190c5790055dffe0b20d8662e98a9ef)

@ShobhitAd, fixed in https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/pull/223/commits/bea7440f1dd52df18c841c4addcbcacd4ecd4a47

2021-02-04 15:07 UTC, ShobhitAd approved these changes

2021-02-12 21:56 UTC, ShobhitAd commented
@KhrystynaDubovyk please resolve merge conflicts on PR

2021-02-12 22:17 UTC, ShobhitAd approved these changes

2021-02-12 22:17 UTC, merged