Feature/sdl 0262 New vehicle data SeatOccupancy
smartdevicelink/sdl_hmi_integration_guidelines pull request #233
Opened 2020-11-26 13:03 UTC by KhrystynaDubovyk

Guidelines updates according to the proposal [SDL-0262 New vehicle data SeatOccupancy](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0262-New-vehicle-data-SeatOccupancy.md) 

This PR is **not ready** for review.

### Summary
Expand `VehicleDataType` enum with new param
Add new struct `SeatStatus`
Add new struct `SeatOccupancy`
Add `seatOccupancy` to SubscribeVehicleData, UnsubscribeVehicleData, GetVehicleData, OnVehicleData RPCs

2020-11-30 16:02 UTC, KhrystynaDubovyk commented
@atiwari9 please review this PR

2020-12-03 16:47 UTC, atiwari9 approved these changes

2020-12-08 10:49 UTC, LitvinenkoIra commented
@JackLivio This PR is ready for Livio review. Thank you!

2021-01-08 20:54 UTC, jacobkeeler requested changes

2021-01-08 20:54 UTC, jacobkeeler commented on docs/VehicleInfo/SubscribeVehicleData/index.md
> +|seatOccupancy|[Common.VehicleDataResult](../../common/structs/#vehicledataresult)|false|
```suggestion
|seatOccupancy|[Common.VehicleDataResult](../../common/structs/#vehicledataresult)|false||
```

2021-01-08 20:54 UTC, jacobkeeler commented on docs/VehicleInfo/UnsubscribeVehicleData/index.md
> +|seatOccupancy|[Common.VehicleDataResult](../../common/structs/#vehicledataresult)|false|
```suggestion
|seatOccupancy|[Common.VehicleDataResult](../../common/structs/#vehicledataresult)|false||
```

2021-01-13 16:48 UTC, jacobkeeler approved these changes

2021-02-02 20:03 UTC, jacobkeeler commented
@LitvinenkoIra please fix conflicts

2021-02-03 16:12 UTC, merged