Feature/sdl 0269 New vehicle data ClimateData
smartdevicelink/sdl_hmi_integration_guidelines pull request #234
Opened 2020-11-26 13:10 UTC by KhrystynaDubovyk

Guidelines updates according to the proposal [SDL-0269 New vehicle data ClimateData](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0269-New-vehicle-data-ClimateData.md) 

This PR is **not ready** for review.

### Summary

Expand `VehicleDataType` enum with new param
Add new struct `ClimateData`
Add `climateData` to SubscribeVehicleData, UnsubscribeVehicleData, GetVehicleData, OnVehicleData RPCs

2020-11-30 16:02 UTC, KhrystynaDubovyk commented
@atiwari9 please review this PR

2020-12-03 16:57 UTC, atiwari9 approved these changes

2020-12-08 10:54 UTC, LitvinenkoIra commented
@JackLivio This PR is ready for Livio review. Thank you!

2021-01-12 22:31 UTC, ShobhitAd requested changes

2021-01-12 22:31 UTC, ShobhitAd commented on docs/Common/Structs/index.md
> +|externalTemperature|[Common.Temperature]()|false||The external temperature in degrees celsius|
```suggestion
|externalTemperature|Common.Temperature|false||The external temperature in degrees celsius|
```

2021-01-12 22:31 UTC, ShobhitAd commented on docs/Common/Structs/index.md
> +|cabinTemperature| [Common.Temperature]|false||Internal ambient cabin temperature in degrees celsius|
```suggestion
|cabinTemperature|Common.Temperature|false||Internal ambient cabin temperature in degrees celsius|
```

2021-01-12 22:31 UTC, ShobhitAd commented on docs/Common/Structs/index.md
> +|atmosphericPressure|float|false|minvalue="0" maxvalue="2000"|Current atmospheric pressure in mBar|
```suggestion
|atmosphericPressure|float|false|minvalue: 0<br>maxvalue: 2000|Current atmospheric pressure in mBar|
```

2021-01-19 15:27 UTC, ShobhitAd approved these changes

2021-02-09 15:03 UTC, ShobhitAd commented
@KhrystynaDubovyk Please resolve merge conflicts

2021-02-10 16:53 UTC, KhrystynaDubovyk commented
@ShobhitAd, done in  https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/pull/234/commits/77d384c01961bd5204731d749273a1754745150b

2021-02-10 18:23 UTC, ShobhitAd requested changes

2021-02-10 18:23 UTC, ShobhitAd commented on docs/Common/Structs/index.md
> +### ClimateData
```suggestion
### ClimateData
```

2021-02-10 22:08 UTC, ShobhitAd approved these changes

2021-02-10 22:08 UTC, merged