Feature/sdl 0205 custom button subscription
smartdevicelink/sdl_hmi_integration_guidelines pull request #254
Opened 2021-07-22 09:31 UTC by KhrystynaDubovyk

❗  NOTE  ❗  : This update is based on [Button Subscription Response from HMI](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/pull/253), so this PR should be merged AFTER #253  

Guidelines updates according to the proposal [SDL-0205 Avoid Custom button subscription in case HMI incompatibility](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0205-Avoid_custom_button_subscription_when_HMI_does_not_support.md)

This PR is [**not ready**] for review.

### Summary
Update SubscribeButton index and assets files, Buttons/GetCapabilities index

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-07-23 11:18 UTC, ashwink11 requested changes

2021-07-23 11:18 UTC, ashwink11 commented on docs/Buttons/SubscribeButton/index.md
> +: Subscribe mob app to a particular button
@KhrystynaDubovyk Could you please correct the typo "mob app"?

2021-07-23 11:18 UTC, ashwink11 commented on docs/Buttons/UnsubscribeButton/index.md
> +: Unsubscribe mob app from a button
@KhrystynaDubovyk Could you please correct the typo "mob app"?

2021-07-23 11:26 UTC, ashwink11 commented
Hi @KhrystynaDubovyk, the file docs/Buttons/UnsubscribeButton/index.md in this PR and in PR #253 seems to be the same. Do we need this file in both PR's?

2021-07-27 14:04 UTC, ashwink11 commented
@jordynmackool this PR is ready for review and is approved by Ford.

2021-08-09 13:28 UTC, iCollin commented on docs/Buttons/GetCapabilities/index.md
> +Check hmi_capabilities, and respond to SDL providing the capabilities of supported buttons.
Could we please add a note here that if the HMI wishes to support soft buttons it must include CUSTOM_BUTTON in these capabilities?

2021-08-12 21:07 UTC, iCollin commented
Could you please merge in develop?

2021-08-13 16:05 UTC, iCollin commented on docs/Buttons/SubscribeButton/assets/SubscribeCUSTOM_BUTTON.txt
> +participant App
@KhrystynaDubovyk Let's add this diagram to `docs/Buttons/SubscribeButton/index.md`

2021-08-13 19:02 UTC, iCollin commented on docs/Buttons/SubscribeButton/assets/SubscribeCUSTOM_BUTTON.txt
> +participant App
```
diff --git a/docs/Buttons/SubscribeButton/index.md b/docs/Buttons/SubscribeButton/index.md
index 7c78176..537909e 100644
--- a/docs/Buttons/SubscribeButton/index.md
+++ b/docs/Buttons/SubscribeButton/index.md
@@ -46,6 +46,11 @@ SubscribeButton
 ![SubscribeButton](./assets/SubscribeButton.png)
 |||
 
+|||
+SubscribeButton CUSTOM_BUTTON
+![SubscribeButton CUSTOM_BUTTON](./assets/SubscribeCUSTOM_BUTTON.png)
+|||
+
 ### JSON Message Examples
 
 #### Example Request
```

2021-08-16 13:48 UTC, iCollin approved these changes

2021-08-16 13:50 UTC, merged