remove OnPutFile parameter FileName
smartdevicelink/sdl_hmi_integration_guidelines pull request #260
Opened 2022-01-27 19:21 UTC by iCollin

https://github.com/smartdevicelink/sdl_core/issues/3153

2022-02-02 22:05 UTC, jacobkeeler requested changes
minor suggestion

2022-02-02 22:05 UTC, jacobkeeler commented on docs/BasicCommunication/OnPutFile/index.md
> +In the context of `PutFile` and `OnPutFile` each of these diagrams refers to `syncFileName` by `FileName`
```suggestion
In the context of `PutFile` and `OnPutFile`, each of these diagrams use the term `FileName` to refer to the value of the `syncFileName` parameter
```

2022-02-03 18:02 UTC, iCollin commented on docs/BasicCommunication/OnPutFile/index.md
> +In the context of `PutFile` and `OnPutFile` each of these diagrams refers to `syncFileName` by `FileName`
Thanks, that sounds better.

2022-02-03 20:10 UTC, jacobkeeler approved these changes

2022-02-03 22:26 UTC, merged